"use client";

import { useEffect, useRef, useState } from "react";
import {
  AlertTriangle,
  CheckCircle2,
  ExternalLink,
  FileCode,
  FolderGit2,
  GitCommitHorizontal,
  GraduationCap,
  Loader2,
  RefreshCw,
  SquareArrowOutUpRight,
  TerminalSquare,
} from "lucide-react";
import { LabTutor } from "@/components/LabTutor";
import { LabMarkdown } from "@/components/LabMarkdown";
import { cursorFileUrl } from "@/lib/cursor-link";
import { openLabWorkspaceInCursor } from "@/lib/open-in-cursor-client";
import { agentLabCommand, openTerminal, type LabLaunchPlan } from "@/lib/terminal-launch";
import { useLive } from "@/lib/use-fetch";
import { useToast } from "@/lib/use-toast";

/** One generated lab, as returned by GET /api/capability/journey. */
export interface LabRecordSummary {
  category: string;
  signalId: string;
  label: string;
  repoName: string;
  generatedAt: string;
  source: string;
  done: boolean;
  completedAt?: string;
  hasWorkspace: boolean;
}

const LAB_BUILT_EVENT = "devhub:lab-built";

/**
 * The list of already-generated labs (optionally per repo), so views can show
 * "built" / "done" state before anyone clicks Build. Revalidates whenever any
 * useLab() in the app finishes generating.
 */
export function useLabRecords(repoName?: string) {
  const key = `/api/capability/journey${repoName ? `?repoName=${encodeURIComponent(repoName)}` : ""}`;
  const { data, mutate } = useLive<{ labs: LabRecordSummary[] }>(key, {
    refreshInterval: 0,
    revalidateOnFocus: false,
  });
  useEffect(() => {
    const onBuilt = () => void mutate();
    window.addEventListener(LAB_BUILT_EVENT, onBuilt);
    return () => window.removeEventListener(LAB_BUILT_EVENT, onBuilt);
  }, [mutate]);
  const records = data?.labs ?? [];
  const bySignal = new Map(records.map((r) => [r.signalId, r]));
  return { records, bySignal };
}

export interface LabState {
  category: string;
  signalId: string;
  repoName: string;
  repoPath: string | null;
  markdown: string;
  source: string;
  stale: boolean;
  done: boolean;
  evidence: { path: string; url: string | null }[];
  introducedCommit: { sha: string; url: string | null } | null;
  workspacePath?: string;
  services: string[];
  starterFiles: string[];
}

function labStateFromResponse(body: Record<string, unknown>, signalId: string): LabState {
  return {
    category: String(body.category ?? ""),
    signalId,
    repoName: String(body.repoName ?? ""),
    repoPath: typeof body.repoPath === "string" ? body.repoPath : null,
    markdown: String(body.markdown ?? ""),
    source: String(body.source ?? "ai"),
    stale: body.stale === true,
    done: body.done === true,
    evidence: Array.isArray(body.evidence) ? (body.evidence as LabState["evidence"]) : [],
    introducedCommit: (body.introducedCommit as LabState["introducedCommit"]) ?? null,
    workspacePath: typeof body.workspacePath === "string" ? body.workspacePath : undefined,
    services: Array.isArray(body.services) ? (body.services as string[]) : [],
    starterFiles: Array.isArray(body.starterFiles) ? (body.starterFiles as string[]) : [],
  };
}

/** How long we wait for the OpenCode agent to build + adopt a lab. */
const BUILD_POLL_MS = 5_000;
const BUILD_TIMEOUT_MS = 15 * 60_000;

/**
 * "Build lab" — labs are generated by the OpenCode agent (capability-lab
 * skill) running visibly in the terminal dock. This hook fetches the plan,
 * launches the agent, then polls until the agent registers the lab via the
 * adopt API. Existing labs load instantly from /api/capability/journey.
 * `repoName` pins the lab to a specific repo (used by the repo-level view).
 * `builtHint` (from useLabRecords) makes the button read "Show lab" for labs
 * that already exist, before anything is loaded.
 */
export function useLab(signalId: string, repoName?: string, builtHint?: boolean) {
  const [lab, setLab] = useState<LabState | null>(null);
  const [loading, setLoading] = useState(false);
  const [busy, setBusy] = useState(false);
  const [open, setOpen] = useState(false);
  const toast = useToast();

  async function fetchExisting(): Promise<LabState | null> {
    const res = await fetch("/api/capability/journey", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ signalId, repoName }),
    });
    const body = (await res.json()) as Record<string, unknown>;
    if (res.ok) return labStateFromResponse(body, signalId);
    if (body.notBuilt === true) return null;
    throw new Error(typeof body.error === "string" && body.error ? body.error : "Couldn't load the lab");
  }

  /** Wait for the agent to adopt the lab (record newer than `since`). */
  async function pollForAdoption(category: string, since: string): Promise<boolean> {
    const deadline = Date.now() + BUILD_TIMEOUT_MS;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, BUILD_POLL_MS));
      try {
        const res = await fetch(`/api/capability/journey${repoName ? `?repoName=${encodeURIComponent(repoName)}` : ""}`);
        const body = (await res.json()) as { labs?: { category: string; generatedAt: string }[] };
        const rec = body.labs?.find((l) => l.category === category);
        if (rec && rec.generatedAt > since) return true;
      } catch {
        // transient — keep polling
      }
    }
    return false;
  }

  async function generate(refresh: boolean) {
    setLoading(true);
    setOpen(true);
    try {
      const planRes = await fetch(
        `/api/capability/journey/plan?signalId=${encodeURIComponent(signalId)}${repoName ? `&repoName=${encodeURIComponent(repoName)}` : ""}`,
      );
      const plan = (await planRes.json()) as (LabLaunchPlan & {
        category: string;
        repoPath: string;
        exists: boolean;
        error?: string;
      });
      if (!planRes.ok) throw new Error(plan.error || "Couldn't plan the lab");

      // Already built and not refreshing → just load it.
      if (plan.exists && !refresh) {
        const existing = await fetchExisting();
        if (existing) {
          setLab(existing);
          return;
        }
      }

      // Build in the terminal via the OpenCode agent, then wait for adoption.
      const launchedAt = new Date().toISOString();
      openTerminal({
        cwd: plan.repoPath,
        label: `lab · ${plan.repoName}/${signalId}`,
        command: await agentLabCommand(plan, refresh),
      });
      toast.info("Building the lab with OpenCode - watch the terminal; it'll appear here when done.");

      const adopted = await pollForAdoption(plan.category, launchedAt);
      if (!adopted) {
        throw new Error("The OpenCode build hasn't finished - check the terminal, then reopen this lab.");
      }
      const built = await fetchExisting();
      if (!built) throw new Error("Lab built but couldn't be loaded - try reopening it.");
      setLab(built);
      window.dispatchEvent(new CustomEvent("devhub:lab-built"));
      toast.success(refresh ? "Lab rebuilt" : `Lab ready for ${built.repoName} · saved to Learnings`);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Lab build failed");
      if (!refresh) setOpen(false);
    } finally {
      setLoading(false);
    }
  }

  async function toggle() {
    if (lab) {
      setOpen((o) => !o);
      return;
    }
    if (loading) return;
    await generate(false);
  }

  async function regenerate() {
    if (loading) return;
    await generate(true);
  }

  async function toggleDone() {
    if (!lab || busy) return;
    setBusy(true);
    const next = !lab.done;
    try {
      const res = await fetch("/api/capability/journey/complete", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ category: lab.category, done: next }),
      });
      const body = (await res.json()) as { error?: string };
      if (!res.ok) throw new Error(body.error || "Update failed");
      setLab({ ...lab, done: next });
      // Keep "Your labs" and every signal row's done-check in sync.
      window.dispatchEvent(new CustomEvent("devhub:lab-built"));
      toast.success(next ? "Lab marked done" : "Lab reopened");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Update failed");
    } finally {
      setBusy(false);
    }
  }

  const label = loading ? "Building…" : lab ? (open ? "Hide lab" : "Show lab") : builtHint ? "Show lab" : "Build lab";
  return { lab, loading, busy, open, toggle, regenerate, toggleDone, label };
}

export function LabButton({
  onClick,
  label,
  done,
  compact,
  loading,
}: {
  onClick: () => void;
  label: string;
  done?: boolean;
  compact?: boolean;
  loading?: boolean;
}) {
  const size = compact ? 11 : 12;
  return (
    <button
      type="button"
      className="btn btn-ghost text-xs"
      style={{ padding: compact ? "3px 7px" : "4px 8px", color: done ? "var(--accent)" : undefined }}
      onClick={onClick}
    >
      {loading ? (
        <Loader2 size={size} className="animate-spin" />
      ) : done ? (
        <CheckCircle2 size={size} className="lab-done-pop" />
      ) : (
        <GraduationCap size={size} />
      )}
      {label}
    </button>
  );
}

/**
 * Renders the right thing for a lab row: nothing when closed, the full panel
 * when a lab is loaded. One component so every call site (radar deltas, drift
 * rows, repo signal rows) stays a one-liner and can't drift.
 */
export function LabSlot({ state, aiConfigured }: { state: ReturnType<typeof useLab>; aiConfigured: boolean }) {
  if (!state.open || !state.lab) return null;
  return (
    <LabPanel
      lab={state.lab}
      aiConfigured={aiConfigured}
      loading={state.loading}
      busy={state.busy}
      onRegenerate={() => void state.regenerate()}
      onToggleDone={() => void state.toggleDone()}
    />
  );
}

/** Section headings (`## …`) → short chip labels for in-lab navigation. */
function labSections(markdown: string): string[] {
  return markdown
    .split("\n")
    .filter((l) => l.startsWith("## "))
    .map((l) => l.slice(3).split(" — ")[0].trim())
    .map((l) => (l.length > 26 ? `${l.slice(0, 25)}…` : l));
}

export function LabPanel({
  lab,
  aiConfigured,
  loading,
  busy,
  onRegenerate,
  onToggleDone,
}: {
  lab: LabState;
  aiConfigured: boolean;
  loading: boolean;
  busy: boolean;
  onRegenerate: () => void;
  onToggleDone: () => void;
}) {
  const toast = useToast();
  const panelRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const [allEvidence, setAllEvidence] = useState(false);
  const sections = labSections(lab.markdown);
  // Long evidence lists read as noise — show the top few, expand on demand.
  const evidence = allEvidence ? lab.evidence : lab.evidence.slice(0, 6);
  const hiddenEvidence = lab.evidence.length - evidence.length;

  // Bring the freshly opened lab into view — rows low on the page otherwise
  // expand off-screen and the click appears to do nothing.
  useEffect(() => {
    panelRef.current?.scrollIntoView({ block: "nearest", behavior: "smooth" });
  }, []);

  function jumpToSection(index: number) {
    const heading = contentRef.current?.querySelectorAll("h2")[index];
    heading?.scrollIntoView({ block: "start", behavior: "smooth" });
  }

  return (
    <div ref={panelRef} className="lab-panel-enter border-t mt-3 pt-3 text-xs" style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}>
      <div className="flex items-center flex-wrap gap-x-2 gap-y-1 mb-2 text-[11px]" style={{ color: "var(--text-subtle)" }}>
        <span>
          Grounded in <strong>{lab.repoName}</strong> · saved to{" "}
          <a href={`/notes/learnings/${lab.category}`} style={{ color: "var(--accent)" }} title="Open this lab's note">
            Learnings
          </a>
        </span>
        {lab.source !== "ai" && <span>· evidence-only</span>}
        <span className="ml-auto flex items-center gap-1">
          <button type="button" className="btn btn-ghost" style={{ padding: "2px 6px" }} onClick={onRegenerate} disabled={loading}>
            <RefreshCw size={11} className={loading ? "animate-spin" : ""} /> Regenerate
          </button>
          <button
            type="button"
            className="btn btn-ghost"
            style={{ padding: "2px 6px", color: lab.done ? "var(--accent)" : undefined }}
            onClick={onToggleDone}
            disabled={busy}
          >
            <CheckCircle2 size={11} /> {lab.done ? "Done" : "Mark done"}
          </button>
        </span>
      </div>

      {lab.stale && (
        <div
          className="flex items-center gap-2 mb-2 rounded px-2 py-1 text-[11px]"
          style={{ background: "var(--warning-dim)", color: "var(--warning)" }}
        >
          <AlertTriangle size={12} className="shrink-0" />
          <span className="flex-1">The repo has moved since this lab was built.</span>
          <button
            type="button"
            className="btn btn-ghost shrink-0"
            style={{ padding: "1px 6px", fontSize: 11, color: "var(--warning)" }}
            onClick={onRegenerate}
            disabled={loading}
          >
            <RefreshCw size={10} className={loading ? "animate-spin" : ""} /> Regenerate now
          </button>
        </div>
      )}

      {sections.length > 1 && (
        <div className="flex flex-wrap gap-1 mb-2">
          {sections.map((s, i) => (
            <button
              key={`${i}-${s}`}
              type="button"
              className="btn btn-ghost"
              style={{ padding: "1px 7px", fontSize: 10, color: "var(--text-subtle)" }}
              onClick={() => jumpToSection(i)}
              title={`Jump to ${s}`}
            >
              {s}
            </button>
          ))}
        </div>
      )}

      {lab.workspacePath && (
        <div
          className="flex items-start gap-2 mb-2 rounded px-2 py-1.5 text-[11px]"
          style={{ background: "var(--bg-muted)" }}
        >
          <FolderGit2 size={13} className="shrink-0 mt-0.5" style={{ color: "var(--accent)" }} />
          <div className="min-w-0 flex-1">
            <div className="flex items-center flex-wrap gap-x-2 gap-y-1">
              <span style={{ color: "var(--text)" }}>
                Hands-on workspace ready
                {lab.services.length > 0 && <> · services: {lab.services.join(", ")}</>}
              </span>
              <span className="ml-auto flex items-center gap-1">
                <button
                  type="button"
                  className="btn btn-ghost"
                  style={{ padding: "2px 6px", fontSize: 11 }}
                  onClick={() => void openLabWorkspaceInCursor(lab.category, toast)}
                  title="Open the workspace folder in Cursor"
                >
                  <SquareArrowOutUpRight size={11} /> Cursor
                </button>
                <button
                  type="button"
                  className="btn btn-ghost"
                  style={{ padding: "2px 6px", fontSize: 11 }}
                  onClick={() =>
                    openTerminal({
                      cwd: lab.workspacePath,
                      label: `lab · ${lab.repoName}/${lab.signalId}`,
                      command: lab.services.length ? "docker compose up -d" : undefined,
                    })
                  }
                  title={
                    lab.services.length
                      ? `Open an in-app terminal in the workspace and start ${lab.services.join(" + ")}`
                      : "Open an in-app terminal in the workspace"
                  }
                >
                  <TerminalSquare size={11} /> Terminal
                </button>
              </span>
            </div>
            <code className="text-[10px] break-all" style={{ color: "var(--text-subtle)" }}>
              {lab.workspacePath}
            </code>
            {lab.services.length > 0 && (
              <div className="text-[10px] mt-0.5" style={{ color: "var(--text-subtle)" }}>
                <code>cd</code> in, then <code>docker compose up -d</code> to start {lab.services.join(" + ")}.
              </div>
            )}
            {lab.starterFiles.length > 0 && (
              <div className="text-[10px] mt-1" style={{ color: "var(--text-subtle)" }}>
                Starter code (AI-generated, review before trusting):{" "}
                {lab.starterFiles.map((f) => (
                  <a
                    key={f}
                    href={cursorFileUrl(`${lab.workspacePath}/${f}`)}
                    className="lab-evidence-link mr-1"
                    style={{ color: "var(--accent)", textDecoration: "none" }}
                    title={`Open ${f} in Cursor`}
                  >
                    <code>{f}</code>
                  </a>
                ))}
              </div>
            )}
          </div>
        </div>
      )}

      <div ref={contentRef}>
        <LabMarkdown text={lab.markdown} fileBase={lab.repoPath ?? undefined} />
      </div>

      {(lab.evidence.length > 0 || lab.introducedCommit) && (
        <div className="mt-3">
          <div className="text-[10px] uppercase tracking-wide mb-1" style={{ color: "var(--text-subtle)" }}>
            Evidence
          </div>
          <div className="flex flex-col gap-0.5">
            {lab.introducedCommit && (
              <EvidenceRef
                icon={<GitCommitHorizontal size={11} />}
                label={`commit ${lab.introducedCommit.sha}`}
                url={lab.introducedCommit.url}
              />
            )}
            {evidence.map((e) => (
              <EvidenceRef
                key={e.path}
                icon={<FileCode size={11} />}
                label={e.path}
                // Local clone → jump straight into Cursor; GitHub stays as a
                // secondary link (pinned at the grounded SHA).
                url={lab.repoPath ? cursorFileUrl(`${lab.repoPath}/${e.path}`) : e.url}
                newTab={!lab.repoPath}
                externalUrl={lab.repoPath ? e.url : null}
              />
            ))}
            {hiddenEvidence > 0 && (
              <button
                type="button"
                className="btn btn-ghost self-start"
                style={{ padding: "1px 6px", fontSize: 10, color: "var(--text-subtle)" }}
                onClick={() => setAllEvidence(true)}
              >
                +{hiddenEvidence} more file{hiddenEvidence === 1 ? "" : "s"}
              </button>
            )}
          </div>
        </div>
      )}

      <div className="mt-3 pt-2 border-t" style={{ borderColor: "var(--border)" }}>
        <LabTutor
          repoName={lab.repoName}
          repoPath={lab.repoPath}
          signalId={lab.signalId}
          category={lab.category}
          aiConfigured={aiConfigured}
        />
      </div>
    </div>
  );
}

function EvidenceRef({
  icon,
  label,
  url,
  newTab = true,
  externalUrl,
}: {
  icon: React.ReactNode;
  label: string;
  url: string | null;
  /** Open the primary link in a new tab (external URLs); editor deep links stay in-place. */
  newTab?: boolean;
  /** Optional secondary link (e.g. GitHub view when the primary opens Cursor). */
  externalUrl?: string | null;
}) {
  const inner = (
    <span className="flex items-center gap-1.5 font-mono text-[11px] truncate">
      <span className="shrink-0" style={{ color: "var(--text-subtle)" }}>
        {icon}
      </span>
      {label}
    </span>
  );
  if (!url) return <div style={{ color: "var(--text-muted)" }}>{inner}</div>;
  return (
    <span className="flex items-center gap-1.5 min-w-0">
      <a
        href={url}
        {...(newTab ? { target: "_blank", rel: "noreferrer" } : {})}
        className="lab-evidence-link min-w-0"
        style={{ color: "var(--accent)", textDecoration: "none" }}
        title={newTab ? undefined : "Open in Cursor"}
      >
        {inner}
      </a>
      {externalUrl && (
        <a
          href={externalUrl}
          target="_blank"
          rel="noreferrer"
          className="shrink-0"
          style={{ color: "var(--text-subtle)" }}
          title="View on GitHub (at the grounded commit)"
          aria-label={`View ${label} on GitHub`}
        >
          <ExternalLink size={10} />
        </a>
      )}
    </span>
  );
}
