/**
 * Capability Radar — weekly evolution digest (Phase 4).
 *
 * Runs an aggregate scan, diffs it against the previous snapshot, and turns the
 * result into a short "what changed in your engineering environment this week"
 * summary: a one-line headline (for the /repos evolution strip) plus a full
 * markdown digest saved to the Learnings archive and a structured cache the
 * /radar page reads. Fully deterministic — no model call — so a scheduled run
 * never depends on AI being configured or funded.
 *
 * Designed to be driven by the in-app scheduler (the `capability_digest`
 * action) on a weekly cron, or on demand via `POST /api/capability/digest`.
 */

import fs from "node:fs";
import path from "node:path";
import { getRepoRoot } from "@/lib/notes-dir";
import { safeReadJSON, writeAtomic } from "@/lib/atomic-write";
import { textToBlocks } from "@/lib/markdown-convert";
import { buildEvolutionHeadline } from "./headline";
import { capabilityCacheDir } from "./paths";
import { runScan } from "./scan";
import type { CapabilityDiff, CapabilitySnapshot, DiffEntry, DriftEntry } from "./types";

export interface CapabilityDigest {
  /** One digest per calendar day (YYYY-MM-DD); reruns overwrite the day. */
  id: string;
  createdAt: string;
  snapshotId: string;
  fromId: string | null;
  headline: string;
  counts: { added: number; spread: number; removed: number; drift: number };
  markdown: string;
  source: "ai" | "deterministic";
}

// ---- pure builders (unit-tested) ----

export function buildDigestHeadline(diff: CapabilityDiff): string {
  return `This week: ${buildEvolutionHeadline(diff)}`;
}

export function digestCounts(diff: CapabilityDiff): CapabilityDigest["counts"] {
  return {
    added: diff.added.length,
    spread: diff.spread.length,
    removed: diff.removed.length,
    drift: diff.drift.length,
  };
}

function entryLine(e: DiffEntry): string {
  const where = e.repos.length ? ` - ${e.repos.slice(0, 4).join(", ")}${e.repos.length > 4 ? "…" : ""}` : "";
  return `- **${e.label}** (${e.area})${where}`;
}

function spreadLine(e: DiffEntry): string {
  return `- **${e.label}** (${e.area}) - ${e.fromRepoCount} → ${e.toRepoCount} repos`;
}

function driftLine(d: DriftEntry): string {
  const stale =
    d.daysSinceMine === null ? "never authored by you" : `${d.daysSinceMine}d since you touched it`;
  const grew = d.repoDelta > 0 ? `, now in ${d.repoDelta} more repo${d.repoDelta === 1 ? "" : "s"}` : "";
  return `- **${d.label}** - ${stale}${grew} (${d.repoCount} repos)`;
}

export function buildDigestMarkdown(snapshot: CapabilitySnapshot, diff: CapabilityDiff): string {
  const lines: string[] = [];
  lines.push(`# ${buildDigestHeadline(diff)}`);
  lines.push("");
  // Note: no `_italics_` — the dashboard markdown renderers don't support them.
  lines.push(
    `${snapshot.repoCount} repos scanned (${snapshot.source.local} local` +
      `${snapshot.source.github ? `, ${snapshot.source.github} remote` : ""}) · ${new Date(snapshot.createdAt).toUTCString()}`,
  );
  lines.push("");

  if (!diff.fromId) {
    lines.push("First scan - this is your baseline. Next week's digest will show what changed.", "");
  }

  if (diff.added.length) {
    lines.push("## New", "", ...diff.added.map(entryLine), "");
  }
  if (diff.spread.length) {
    lines.push("## Spreading", "", ...diff.spread.map(spreadLine), "");
  }
  if (diff.removed.length) {
    lines.push("## Retired", "", ...diff.removed.map(entryLine), "");
  }
  if (diff.drift.length) {
    lines.push("## Knowledge drift - worth a lab", "", ...diff.drift.map(driftLine), "");
  }
  if (diff.fromId && !diff.added.length && !diff.spread.length && !diff.removed.length && !diff.drift.length) {
    lines.push("No changes since the last scan. Steady state.", "");
  }

  lines.push("---", "Generated by Capability Radar. Open /radar to explore or build a lab.");
  return lines.join("\n");
}

// ---- persistence ----

function digestsCacheDir(): string {
  return capabilityCacheDir("digests");
}
function digestCacheFile(id: string): string {
  return path.join(digestsCacheDir(), `${id}.json`);
}
function digestLearningFile(id: string): string {
  return path.join(getRepoRoot(), "notes", "learnings", "digests", `${id}.json`);
}

export function listDigests(): CapabilityDigest[] {
  const dir = digestsCacheDir();
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => safeReadJSON<CapabilityDigest | null>(path.join(dir, f), null))
    .filter((d): d is CapabilityDigest => d !== null)
    .sort((a, b) => b.id.localeCompare(a.id));
}

export function readLatestDigest(): CapabilityDigest | null {
  return listDigests()[0] ?? null;
}

// ---- orchestration ----

export interface DigestOptions {
  includeGithub?: boolean;
  githubFilter?: string;
  /** Skip persisting to the Learnings archive (used by tests / dry runs). */
  skipLearningNote?: boolean;
  emit?: (line: string) => void;
}

export async function runDigest(opts: DigestOptions = {}): Promise<CapabilityDigest> {
  const emit = opts.emit ?? (() => {});
  emit("Scanning repositories…");
  const { snapshot, diff, warnings } = await runScan({
    includeGithub: opts.includeGithub,
    githubFilter: opts.githubFilter,
  });
  for (const w of warnings) emit(`⚠ ${w}`);
  emit(`Scanned ${snapshot.repoCount} repos. Building digest…`);

  const id = new Date().toISOString().slice(0, 10);
  const markdown = buildDigestMarkdown(snapshot, diff);
  const digest: CapabilityDigest = {
    id,
    createdAt: new Date().toISOString(),
    snapshotId: snapshot.id,
    fromId: diff.fromId,
    headline: buildDigestHeadline(diff),
    counts: digestCounts(diff),
    markdown,
    source: "deterministic",
  };

  // Structured cache for the /radar UI.
  try {
    fs.mkdirSync(digestsCacheDir(), { recursive: true });
    await writeAtomic(digestCacheFile(id), JSON.stringify(digest));
  } catch (err) {
    emit(`Failed to cache digest: ${String(err).slice(0, 120)}`);
  }

  // Browsable note in the Learnings archive.
  if (!opts.skipLearningNote) {
    try {
      const file = digestLearningFile(id);
      fs.mkdirSync(path.dirname(file), { recursive: true });
      await writeAtomic(file, JSON.stringify(textToBlocks(markdown)));
    } catch (err) {
      emit(`Failed to save digest note: ${String(err).slice(0, 120)}`);
    }
  }

  emit(`Digest ready: ${digest.headline}`);
  return digest;
}
