/**
 * Capability Radar — journey / lab plumbing.
 *
 * Labs are GENERATED by the OpenCode agent (the `capability-lab` skill, run
 * visibly in the terminal dock — same pattern as PR review). This module owns
 * the deterministic sides of that contract:
 *
 *  - `planLab`   — everything the agent needs to build a lab (target repo,
 *                  evidence + introducing commit, workspace dir, services,
 *                  starter language, notes path).
 *  - `getLab`    — read an existing lab for the UI (never generates).
 *  - `adoptLab`  — called (via the adopt API) after the agent writes the note:
 *                  verifies citations, scaffolds the workspace baseline,
 *                  records starter files, creates the follow-up task, and
 *                  persists the lab record the UI reads.
 *
 * The lab note itself lives in the Learnings archive
 * (`notes/learnings/labs/<repo>/<signal>.json`, editor blocks), written by the
 * agent through the notes MCP.
 */

import fs from "node:fs";
import path from "node:path";
import { getRepoRoot } from "@/lib/notes-dir";
import { getReposScanDir } from "@/lib/repos";
import { safeReadJSON, writeAtomic } from "@/lib/atomic-write";
import { blocksToText } from "@/lib/markdown-convert";
import { addTask, getTasks, toggleTask } from "@/lib/tasks-storage";
import { todayISO } from "@/lib/utils";
import { gitLog } from "./git";
import { capabilityCacheDir, safeSegment } from "./paths";
import {
  labWorkspaceDir,
  listStarterFiles,
  scaffoldLabWorkspace,
  servicesForSignal,
} from "./lab-workspace";
import type { CapabilitySnapshot, RepoScan, SignalRollup } from "./types";

export interface EvidenceLink {
  path: string;
  /** GitHub blob URL at the grounded SHA, when the remote is known. */
  url: string | null;
}

export interface LabArtifact {
  signalId: string;
  label: string;
  repoName: string;
  /** Absolute local path of the grounding repo (for editor deep links). */
  repoPath: string | null;
  /** Learnings category / relative path (no extension), e.g. "labs/frigga/flux". */
  category: string;
  markdown: string;
  generatedAt: string;
  source: "ai" | "evidence-only";
  /** Follow-up task id, when one was created. */
  taskId?: string;
  /** Repo HEAD the lab was grounded in. */
  groundedSha: string | null;
  /** True when the repo has moved past groundedSha (lab may be out of date). */
  stale: boolean;
  /** Clickable evidence files. */
  evidence: EvidenceLink[];
  /** Introducing commit, linkified when the remote is known. */
  introducedCommit: { sha: string; url: string | null } | null;
  /** Cited paths that couldn't be found in the repo (possible hallucinations). */
  unverifiedPaths: string[];
  /** Absolute path to the hands-on workspace directory, when scaffolded. */
  workspacePath?: string;
  /** Local services the workspace spins up (e.g. ["mongo"]). */
  services?: string[];
  /** Relative paths of AI-generated starter files under the workspace. */
  starterFiles?: string[];
  /** Completion state. */
  done: boolean;
  completedAt?: string;
}

/** Structured metadata persisted alongside each lab (gitignored cache). */
export interface LabRecord {
  category: string;
  signalId: string;
  label: string;
  repoName: string;
  repoRemoteUrl: string | null;
  groundedSha: string | null;
  introducedSha: string | null;
  evidence: string[];
  unverifiedPaths: string[];
  workspacePath?: string;
  services?: string[];
  starterFiles?: string[];
  taskId?: string;
  taskDate?: string;
  generatedAt: string;
  source: "ai" | "evidence-only";
  done: boolean;
  completedAt?: string;
}

interface LabEvidence {
  repoName: string;
  repoRemoteUrl: string | null;
  groundedSha: string | null;
  introducedSha: string | null;
  evidencePaths: string[];
  introduced: string | null; // "<sha> <subject> (<date>)"
  recent: string[];
}

// ---- path helpers ----

export function labCategory(repoName: string, signalId: string): string {
  return `labs/${safeSegment(repoName)}/${safeSegment(signalId)}`;
}

function labFile(category: string): string {
  return path.join(getRepoRoot(), "notes", "learnings", `${category}.json`);
}

// ---- lab record store (gitignored cache) ----

function labsRecordDir(): string {
  return capabilityCacheDir("labs");
}
function recordFile(category: string): string {
  return path.join(labsRecordDir(), `${safeSegment(category, "__")}.json`);
}

export function readLabRecord(category: string): LabRecord | null {
  return safeReadJSON<LabRecord | null>(recordFile(category), null);
}

export function listLabRecords(): LabRecord[] {
  const dir = labsRecordDir();
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .map((f) => safeReadJSON<LabRecord | null>(path.join(dir, f), null))
    .filter((r): r is LabRecord => r !== null);
}

async function writeLabRecord(rec: LabRecord): Promise<void> {
  const file = recordFile(rec.category);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  await writeAtomic(file, JSON.stringify(rec));
}

// ---- resumable tutor session (transcript per lab) ----

function sessionsDir(): string {
  return capabilityCacheDir("sessions");
}
function sessionFile(category: string): string {
  return path.join(sessionsDir(), `${safeSegment(category, "__")}.json`);
}

export interface LabSession {
  messages: unknown[];
  updatedAt: string;
}

export function readLabSession(category: string): LabSession | null {
  return safeReadJSON<LabSession | null>(sessionFile(category), null);
}

export async function writeLabSession(category: string, messages: unknown[]): Promise<void> {
  const file = sessionFile(category);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  await writeAtomic(file, JSON.stringify({ messages, updatedAt: new Date().toISOString() }));
}

export function clearLabSession(category: string): void {
  try {
    fs.rmSync(sessionFile(category), { force: true });
  } catch {
    // best-effort
  }
}

// ---- remote + evidence links ----

/** Normalise a git remote (scp/ssh/https) to an https base URL, or null. */
export function normalizeGitRemote(url: string | null): string | null {
  if (!url) return null;
  let u = url.trim().replace(/\.git$/, "");
  const scp = u.match(/^git@([^:]+):(.+)$/); // git@github.com:org/repo
  if (scp) u = `https://${scp[1]}/${scp[2]}`;
  u = u.replace(/^ssh:\/\/git@/, "https://").replace(/^git:\/\//, "https://");
  return /^https?:\/\//.test(u) ? u : null;
}

export function buildEvidenceLinks(
  paths: string[],
  remoteUrl: string | null,
  sha: string | null,
): EvidenceLink[] {
  return paths.map((p) => ({
    path: p,
    url: remoteUrl && sha ? `${remoteUrl}/blob/${sha}/${p}` : null,
  }));
}

function commitLink(sha: string | null, remoteUrl: string | null): { sha: string; url: string | null } | null {
  if (!sha) return null;
  return { sha, url: remoteUrl ? `${remoteUrl}/commit/${sha}` : null };
}

// ---- grounding guardrail ----

/** Backticked tokens in the markdown that look like repo file paths. */
export function extractCitedPaths(markdown: string): string[] {
  const paths = new Set<string>();
  const re = /`([^`]+)`/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(markdown))) {
    const tok = m[1].trim();
    if (/\s/.test(tok) || !tok.includes("/")) continue; // needs a path separator, no spaces
    if (/:\/\/|@/.test(tok)) continue; // skip URLs / git remotes (git@…, ssh://…, https://…)
    if (!/\.[A-Za-z0-9]+$/.test(tok) && !/\/[A-Za-z0-9_.-]+$/.test(tok)) continue;
    paths.add(tok.replace(/[),.;:]+$/, ""));
  }
  return [...paths];
}

/** Cited paths that are neither in the evidence set nor present on disk. */
export function verifyCitedPaths(markdown: string, evidencePaths: string[], repoRef: string): string[] {
  const evidence = new Set(evidencePaths);
  const unverified: string[] = [];
  for (const p of extractCitedPaths(markdown)) {
    if (evidence.has(p)) continue;
    const full = path.join(repoRef, p);
    if (path.resolve(full).startsWith(path.resolve(repoRef)) && fs.existsSync(full)) continue;
    unverified.push(p);
  }
  return unverified.slice(0, 12);
}

function toArtifact(rec: LabRecord, markdown: string, currentSha: string | null): LabArtifact {
  return {
    signalId: rec.signalId,
    label: rec.label,
    repoName: rec.repoName,
    repoPath: rec.repoName ? path.join(getReposScanDir(), rec.repoName) : null,
    category: rec.category,
    markdown,
    generatedAt: rec.generatedAt,
    source: rec.source,
    taskId: rec.taskId,
    groundedSha: rec.groundedSha,
    stale: !!(rec.groundedSha && currentSha && rec.groundedSha !== currentSha),
    evidence: buildEvidenceLinks(rec.evidence, rec.repoRemoteUrl, rec.groundedSha),
    introducedCommit: commitLink(rec.introducedSha, rec.repoRemoteUrl),
    unverifiedPaths: rec.unverifiedPaths,
    workspacePath: rec.workspacePath,
    services: rec.services,
    starterFiles: rec.starterFiles,
    done: rec.done,
    completedAt: rec.completedAt,
  };
}

/** Read a saved lab as an artifact, computing staleness against `currentSha`. */
export function readLabView(category: string, currentSha: string | null): LabArtifact | null {
  const blocks = safeReadJSON<unknown[] | null>(labFile(category), null);
  if (!blocks) return null;
  const markdown = blocksToText(blocks);
  const rec = readLabRecord(category);
  if (rec) return toArtifact(rec, markdown, currentSha);
  return {
    signalId: "",
    label: "",
    repoName: "",
    repoPath: null,
    category,
    markdown,
    generatedAt: new Date().toISOString(),
    source: "ai",
    groundedSha: null,
    stale: false,
    evidence: [],
    introducedCommit: null,
    unverifiedPaths: [],
    done: false,
  };
}

/** Mark a lab complete (or reopen) and reflect it on the follow-up task. */
export async function markLabComplete(category: string, done = true): Promise<LabRecord | null> {
  const rec = readLabRecord(category);
  if (!rec) return null;
  rec.done = done;
  rec.completedAt = done ? new Date().toISOString() : undefined;
  await writeLabRecord(rec);
  if (rec.taskId) {
    try {
      const task = getTasks(rec.taskDate).find((t) => t.id === rec.taskId);
      if (task && task.done !== done) await toggleTask(rec.taskId, rec.taskDate);
    } catch {
      // best-effort — the record is the source of truth
    }
  }
  return rec;
}

/**
 * The language the starter project should be written in, derived from the
 * grounding repo's detected runtime. TypeScript is the learner's primary stack,
 * so it wins whenever the repo has any JS/TS footprint — and is the default
 * when the repo's runtime is unclear (e.g. pure-infra repos). Only repos that
 * are unambiguously Go/Python/Rust (and not also Node) get their own language.
 */
export function preferredStarterLanguage(repo: RepoScan): string {
  const ids = new Set(repo.signals.map((s) => s.id));
  if (ids.has("typescript") || ids.has("node") || ids.has("nextjs")) return "TypeScript (Node.js)";
  if (ids.has("go")) return "Go";
  if (ids.has("python")) return "Python";
  if (ids.has("rust")) return "Rust";
  return "TypeScript (Node.js)";
}

/**
 * Pick the local repo that best grounds a lab for this signal: the one where the
 * signal has the most evidence (falls back to any repo it appears in). Remote-
 * only repos can't ground a hands-on lab, so they're skipped.
 */
export function pickTargetRepo(
  snapshot: CapabilitySnapshot,
  rollup: SignalRollup,
  preferred?: string,
): RepoScan | null {
  const candidates = snapshot.repos.filter(
    (r) => r.source === "local" && r.signals.some((s) => s.id === rollup.id),
  );
  if (candidates.length === 0) return null;
  if (preferred) {
    const match = candidates.find((r) => r.repoName === preferred);
    if (match) return match;
  }
  return candidates.sort((a, b) => {
    const sa = a.signals.find((s) => s.id === rollup.id);
    const sb = b.signals.find((s) => s.id === rollup.id);
    return (sb?.evidence.length ?? 0) - (sa?.evidence.length ?? 0) || (sb?.confidence ?? 0) - (sa?.confidence ?? 0);
  })[0];
}

// ---- evidence gathering ----

async function gatherEvidence(repo: RepoScan, rollup: SignalRollup): Promise<LabEvidence> {
  const sig = repo.signals.find((s) => s.id === rollup.id);
  const evidencePaths = (sig?.evidence ?? []).slice(0, 10);

  const introduced = evidencePaths.length
    ? await gitLog(repo.repoRef, ["log", "--diff-filter=A", "-1", "--format=%h %s (%cs)", "--", ...evidencePaths])
    : "";
  const introducedSha = evidencePaths.length
    ? await gitLog(repo.repoRef, ["log", "--diff-filter=A", "-1", "--format=%h", "--", ...evidencePaths])
    : "";
  const recentRaw = evidencePaths.length
    ? await gitLog(repo.repoRef, ["log", "-3", "--format=%h %s (%cs)", "--", ...evidencePaths])
    : "";
  const remoteRaw = await gitLog(repo.repoRef, ["config", "--get", "remote.origin.url"]);

  return {
    repoName: repo.repoName,
    repoRemoteUrl: normalizeGitRemote(remoteRaw || null),
    groundedSha: repo.sha,
    introducedSha: introducedSha || null,
    evidencePaths,
    introduced: introduced || null,
    recent: recentRaw ? recentRaw.split("\n").filter(Boolean) : [],
  };
}

// ---- plan / get / adopt (generation itself happens in OpenCode) ----

function resolveTarget(
  snapshot: CapabilitySnapshot,
  signalId: string,
  repoName?: string,
): { rollup: SignalRollup; repo: RepoScan; category: string } {
  const rollup = snapshot.signals[signalId];
  if (!rollup) throw new Error(`Unknown signal: ${signalId}`);
  const repo = pickTargetRepo(snapshot, rollup, repoName);
  if (!repo) throw new Error(`No local repo grounds "${rollup.label}" - clone one of: ${rollup.repos.join(", ")}`);
  return { rollup, repo, category: labCategory(repo.repoName, rollup.id) };
}

/** Everything the capability-lab OpenCode skill needs to build a lab. */
export interface LabPlan {
  signalId: string;
  label: string;
  kind: string;
  area: string;
  category: string;
  repoName: string;
  /** Absolute path of the grounding repo clone. */
  repoPath: string;
  /** Absolute workspace directory (under kitchen-sink) for the hands-on files. */
  workspacePath: string;
  services: string[];
  language: string;
  evidence: string[];
  /** Introducing commit line, when found ("<sha> <subject> (<date>)"). */
  introduced: string | null;
  recent: string[];
  /** Notes MCP path for the lab note (e.g. "learnings/labs/capi/mongodb"). */
  notePath: string;
  /** True when a lab note already exists (Show vs Build). */
  exists: boolean;
}

export async function planLab(
  snapshot: CapabilitySnapshot,
  opts: { signalId: string; repoName?: string },
): Promise<LabPlan> {
  const { rollup, repo, category } = resolveTarget(snapshot, opts.signalId, opts.repoName);
  const ev = await gatherEvidence(repo, rollup);
  return {
    signalId: rollup.id,
    label: rollup.label,
    kind: rollup.kind,
    area: rollup.area,
    category,
    repoName: repo.repoName,
    repoPath: repo.repoRef,
    workspacePath: labWorkspaceDir(repo.repoName, rollup.id),
    services: servicesForSignal(rollup.id, rollup.label).map((s) => s.name),
    language: preferredStarterLanguage(repo),
    evidence: ev.evidencePaths,
    introduced: ev.introduced,
    recent: ev.recent,
    notePath: `learnings/${category}`,
    exists: fs.existsSync(labFile(category)),
  };
}

/** Read an existing lab for the UI. Never generates — that's OpenCode's job. */
export function getLab(
  snapshot: CapabilitySnapshot,
  opts: { signalId: string; repoName?: string },
): LabArtifact | null {
  const { repo, category } = resolveTarget(snapshot, opts.signalId, opts.repoName);
  return readLabView(category, repo.sha);
}

export interface AdoptOptions {
  signalId: string;
  repoName?: string;
  /** Skip creating a follow-up task (used by tests). Default false. */
  noTask?: boolean;
}

/**
 * Register a lab the OpenCode agent just built: read the note it saved,
 * verify citations, scaffold the deterministic workspace baseline (README /
 * STEPS / compose — the agent's `starter/` files are left untouched), create
 * the follow-up task on first adoption, and persist the lab record.
 */
export async function adoptLab(
  snapshot: CapabilitySnapshot,
  opts: AdoptOptions,
): Promise<LabArtifact> {
  const { rollup, repo, category } = resolveTarget(snapshot, opts.signalId, opts.repoName);

  const blocks = safeReadJSON<unknown[] | null>(labFile(category), null);
  if (!blocks) {
    throw new Error(`No lab note at learnings/${category} - the capability-lab skill must write it (notes_write) first.`);
  }
  const markdown = blocksToText(blocks);

  const ev = await gatherEvidence(repo, rollup);
  const unverifiedPaths = verifyCitedPaths(markdown, ev.evidencePaths, repo.repoRef);

  // Preserve done-state + original follow-up task across regenerations.
  const prior = readLabRecord(category);

  let taskId = prior?.taskId;
  let taskDate = prior?.taskDate;
  if (!prior && !opts.noTask) {
    try {
      // Link to the live learn screen (lab + tutor + workspace), deep-linked to
      // this signal — not the static Learnings note.
      const task = await addTask(
        `Lab: [${rollup.label} in ${repo.repoName}](/repos/learn/${encodeURIComponent(repo.repoName)}?lab=${encodeURIComponent(rollup.id)})`,
      );
      taskId = task.id;
      taskDate = todayISO();
    } catch {
      // task creation is best-effort
    }
  }

  // Deterministic workspace baseline; the agent's starter/ files are preserved
  // (scaffold only writes starter files when given some, which we never do here).
  const workspace = scaffoldLabWorkspace({
    category,
    repoName: repo.repoName,
    signalId: rollup.id,
    label: rollup.label,
    markdown,
    remoteUrl: ev.repoRemoteUrl,
    evidencePaths: ev.evidencePaths,
    starter: null,
  });
  const workspacePath = workspace?.workspacePath ?? labWorkspaceDir(repo.repoName, rollup.id);
  const starterFiles = listStarterFiles(workspacePath);

  const record: LabRecord = {
    category,
    signalId: rollup.id,
    label: rollup.label,
    repoName: repo.repoName,
    repoRemoteUrl: ev.repoRemoteUrl,
    groundedSha: ev.groundedSha,
    introducedSha: ev.introducedSha,
    evidence: ev.evidencePaths,
    unverifiedPaths,
    workspacePath: fs.existsSync(workspacePath) ? workspacePath : undefined,
    services: workspace?.services ?? [],
    starterFiles,
    taskId,
    taskDate,
    generatedAt: new Date().toISOString(),
    source: "ai",
    done: prior?.done ?? false,
    completedAt: prior?.completedAt,
  };
  await writeLabRecord(record);

  return toArtifact(record, markdown, repo.sha);
}
